[global]
    # the name will validate join cluster by same name
    name = "cbdb"
    # you data save to disk path ,If you are in a production environment, You'd better set absolute paths
    data = [
            "/export/vearchdb-ps/datas/",
        ]  
    # log path , If you are in a production environment, You'd better set absolute paths
    log = "/export/vearchdb-ps/logs/"
    # default log type for any model
    level = "debug"
    # master <-> ps <-> router will use this key to send or receive data
    signkey = "cbdb"
    # skip auth for master and router
    skip_auth = true

# if you are master you'd better set all config for router and ps and router and ps use default config it so cool
[[masters]]
    #name machine name for cluster
    name = "master1"
    #ip or domain
    address = "11.40.226.67"
    # api port for http server
    api_port = 8817
    # port for etcd server
    etcd_port = 2378
    # listen_peer_urls List of comma separated URLs to listen on for peer traffic.
    # advertise_peer_urls List of this member's peer URLs to advertise to the rest of the cluster. The URLs needed to be a comma-separated list.
    etcd_peer_port = 2390
    # List of this member's client URLs to advertise to the public.
    # The URLs needed to be a comma-separated list.
    # advertise_client_urls AND listen_client_urls
    etcd_client_port = 2370
    data = ["/export/vearchdb-master/datas/"]
[[masters]]
    #name machine name for cluster
    name = "master2"
    #ip or domain
    address = "11.40.226.68"
    # api port for http server
    api_port = 8817
    # port for etcd server
    etcd_port = 2378
    # listen_peer_urls List of comma separated URLs to listen on for peer traffic.
    # advertise_peer_urls List of this member's peer URLs to advertise to the rest of the cluster. The URLs needed to be a comma-separated list.
    etcd_peer_port = 2390
    # List of this member's client URLs to advertise to the public.
    # The URLs needed to be a comma-separated list.
    # advertise_client_urls AND listen_client_urls
    etcd_client_port = 2370
    data = ["/export/vearchdb-master/datas/"]
[[masters]]
    #name machine name for cluster
    name = "master3"
    #ip or domain
    address = "11.40.226.69"
    # api port for http server
    api_port = 8817
    # port for etcd server
    etcd_port = 2378
    # listen_peer_urls List of comma separated URLs to listen on for peer traffic.
    # advertise_peer_urls List of this member's peer URLs to advertise to the rest of the cluster. The URLs needed to be a comma-separated list.
    etcd_peer_port = 2390
    # List of this member's client URLs to advertise to the public.
    # The URLs needed to be a comma-separated list.
    # advertise_client_urls AND listen_client_urls
    etcd_client_port = 2370
    data = ["/export/vearchdb-master/datas/"]
[router]
    # port for server
    port = 9001
    fix_name = 0
[ps]
    # port for server
    rpc_port = 8081
    #raft config begin
    raft_heartbeat_port = 8898
    raft_replicate_port = 8899
    heartbeat-interval = 200 #ms
    raft_retain_logs = 10000
    raft_replica_concurrency = 1
    raft_snap_concurrency = 1
    journal_enabled = true
    max_size = 50000000000
    pprof_port = 6060
    engine_dwpt_num = 1

