language: python

services:
  - docker

before_install:
  - docker pull docker.io/ansj/vearch_env:0.3
  - docker tag docker.io/ansj/vearch_env:0.3 vearch_env
  - docker images
  - cd cloud
  - echo "Compile Vearch"
  - ./compile.sh
  - echo "Make Vearch Image"
  - ./build.sh
  - echo "Start service by all in one model"
  - cat ../config/config.toml.example > config.toml
  - nohup docker run -p 8817:8817 -p 9001:9001 -v $PWD/config.toml:/vearch/config.toml ansj/vearch:0.3 all &
  - sleep 30
  - cat nohup.out
  - cd ../test

install :
  - pip install requests

script:
  - pytest
